# Generated by Django 2.1.4 on 2019-01-11 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='Ask_A_Question_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ask a question',
            },
        ),
        migrations.CreateModel(
            name='Category_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Astrophysicist', 'Astrophysicist'), ('Civil Engineering', 'Civil Engineering'), ('Politics', 'Politics')], max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Has_Voted_Per_Question_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Has the user answered this questions via voting?',
            },
        ),
        migrations.CreateModel(
            name='Questions_Votes_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
            ],
            options={
                'verbose_name_plural': 'Question and Votes',
            },
        ),
        migrations.CreateModel(
            name='User_Questions_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User and Question',
            },
        ),
        migrations.CreateModel(
            name='User_Questions_Votes_Answers_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Answer_table')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User and Questions and Answers',
            },
        ),
        migrations.CreateModel(
            name='User_Vote_A_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('ask_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users and Vote A',
            },
        ),
        migrations.CreateModel(
            name='User_Vote_B_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('ask_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users and Vote B',
            },
        ),
        migrations.CreateModel(
            name='User_Vote_C_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('ask_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users and Vote C',
            },
        ),
        migrations.CreateModel(
            name='Vote_A_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.TextField()),
                ('total_votes', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vote A',
            },
        ),
        migrations.CreateModel(
            name='Vote_B_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.TextField()),
                ('total_votes', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vote B',
            },
        ),
        migrations.CreateModel(
            name='Vote_C_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.TextField()),
                ('total_votes', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vote C',
            },
        ),
        migrations.CreateModel(
            name='Votes_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('vote_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_A_table')),
                ('vote_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_B_table')),
                ('vote_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_C_table')),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.AddField(
            model_name='user_vote_c_table',
            name='vote_c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_C_table'),
        ),
        migrations.AddField(
            model_name='user_vote_b_table',
            name='vote_b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_B_table'),
        ),
        migrations.AddField(
            model_name='user_vote_a_table',
            name='vote_a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_A_table'),
        ),
        migrations.AddField(
            model_name='questions_votes_table',
            name='votes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Votes_table'),
        ),
    ]
