# Generated by Django 2.1.4 on 2019-01-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='has_voted_per_question_table',
            name='user_vote_a',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.User_Vote_A_table'),
            preserve_default=False,
        ),
    ]
