# Generated by Django 2.1.4 on 2019-01-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_has_voted_per_question_table_user_vote_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='has_voted_per_question_table',
            name='user_vote_a',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User_Vote_A_table'),
        ),
    ]
