# Generated by Django 2.1.4 on 2018-12-30 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20181230_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Questions_Votes_Answers_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Answer_table')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ask_A_Question_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User and Questions and Answers',
            },
        ),
        migrations.CreateModel(
            name='User_Vote_A_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote_a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_A_table')),
            ],
            options={
                'verbose_name_plural': 'Users and Vote A',
            },
        ),
        migrations.CreateModel(
            name='User_Vote_B_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote_b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_B_table')),
            ],
            options={
                'verbose_name_plural': 'Users and Vote B',
            },
        ),
        migrations.CreateModel(
            name='User_Vote_C_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote_c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vote_C_table')),
            ],
            options={
                'verbose_name_plural': 'Users and Vote C',
            },
        ),
    ]
