# Generated by Django 2.1.4 on 2019-01-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190112_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='has_voted_per_question_table',
            name='user_vote_a',
        ),
        migrations.RemoveField(
            model_name='has_voted_per_question_table',
            name='user_vote_b',
        ),
        migrations.RemoveField(
            model_name='has_voted_per_question_table',
            name='user_vote_c',
        ),
    ]
