# Generated by Django 2.1.4 on 2019-01-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190112_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='has_voted_per_question_table',
            name='vote_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Vote_A_table'),
        ),
    ]
