# Generated by Django 2.1.4 on 2019-01-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190112_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='has_voted_per_question_table',
            name='vote_type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
