# Generated by Django 2.1.4 on 2019-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190113_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_questions_votes_answers_table',
            name='vote_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
